#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate a C header from immutable original cluster assets: gen_op1_cluster.py OUT.h.

main(path) is the generator entry point for tools/build.py. Builds do not read
.omo/evidence. Extracted asset rights are documented in assets/op1-cluster/README.md.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Final, TypedDict

ASSETS: Final = Path(__file__).resolve().parents[1] / "assets/op1-cluster"
TABLES_SHA256: Final = "09e4cd8702ef5a3222c9d19c814bea79f1eb8a6afdbbfdcd7c1190000f097f61"
FACTORY_SHA256: Final = "298aeec4c17833e13919c59caad64372844a0f844fd0ef2d115ce5abc77c4408"


class Tables(TypedDict):
    wave: list[int]
    count: list[int]
    curve: list[int]
    master: int


class FactoryRow(TypedDict):
    id: int
    folder: str
    raw_json: str


class Factory(TypedDict):
    database_sha256: str
    default_params_raw: str
    patches: list[FactoryRow]


class Patch(TypedDict):
    name: str
    knobs: list[int]


class AssetMismatch(RuntimeError):
    """An immutable original asset differs from its recorded hash."""

    def __init__(self, path: Path) -> None:
        self.path = path
        super().__init__(f"Original cluster asset hash mismatch: {path}")


def main(path: str) -> None:
    """Emit immutable original signed integers into one header without conversion."""
    tables_bytes = (ASSETS / "tables.json").read_bytes()
    factory_bytes = (ASSETS / "factory.json").read_bytes()
    for filename, data, expected in (
        ("tables.json", tables_bytes, TABLES_SHA256),
        ("factory.json", factory_bytes, FACTORY_SHA256),
    ):
        if hashlib.sha256(data).hexdigest() != expected:
            raise AssetMismatch(ASSETS / filename)
    tables: Tables = json.loads(tables_bytes)
    factory: Factory = json.loads(factory_bytes)
    patches: list[Patch] = [json.loads(row["raw_json"]) for row in factory["patches"]]
    width = max(len(patch["name"].encode("ascii")) for patch in patches) + 1
    lines = [
        "/* Generated by tools/gen_op1_cluster.py from immutable original data.",
        " * Generator code: SPDX-License-Identifier: GPL-3.0-only.",
        " * Original data is not relicensed: assets/op1-cluster/README.md. */",
        "#ifndef FELUCCA_OP1_CLUSTER_H",
        "#define FELUCCA_OP1_CLUSTER_H",
        '#include "op1_cluster_core.h"',
        "static const cls_tables OP1_CLUSTER_TABLES = {",
    ]
    for field, values in (
        ("wave", tables["wave"]),
        ("count", tables["count"]),
        ("curve", tables["curve"]),
    ):
        lines.append(f"    .{field} = {{")
        for index in range(0, len(values), 16):
            lines.append("        " + ", ".join(str(x) for x in values[index:index + 16]) + ",")
        lines.append("    },")
    lines.extend(["};", "static const int16_t OP1_CLUSTER_KNOBS[16][8] = {"])
    for patch in patches:
        lines.append("    {" + ", ".join(str(x) for x in patch["knobs"]) + "},")
    lines.extend(["};", f"static const char OP1_CLUSTER_NAMES[16][{width}] = {{"])
    for patch in patches:
        lines.append("    " + json.dumps(patch["name"], ensure_ascii=True) + ",")
    lines.extend(["};", "#endif", ""])
    Path(path).write_text("\n".join(lines), encoding="utf-8")
    print(f"op1 cluster: {len(patches)} patches, immutable tables -> {path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("Usage: python3 tools/gen_op1_cluster.py OUT.h")
    main(sys.argv[1])
